version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: event-postgres
    restart: always
    environment:
      POSTGRES_USER: bookingadmin
      POSTGRES_PASSWORD: Eel36sWd
      POSTGRES_DB: event_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    build: ./backend-node
    ports:
      - "5051:5050"
    volumes:
      - ./backend-node:/app
      - node_node_modules:/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://bookingadmin:Eel36sWd@postgres:5432/event_platform

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  node_node_modules: